export const APP_BRAND_NAME = "מנלו קודקס";
export const APP_BRAND_SHORT_NAME = "קודקס";
export const APP_BRAND_TAGLINE = "מערכת ניהול לקבלן בניין";
export const APP_DEFAULT_ORG_NAME = "מנלו בנייה";
export const APP_DRIVE_ROOT_FOLDER = "מנלו בנייה";
export const APP_PRODUCTION_URL = "https://menlo-codex.vercel.app";
export const APP_ASSET_VERSION = "2026-05-11-7";
export const APP_PWA_CACHE_VERSION = APP_ASSET_VERSION;
export const APP_ICON_192 = `/generated-app-icon-192.png?v=${APP_ASSET_VERSION}`;
export const APP_ICON_512 = `/generated-app-icon-512.png?v=${APP_ASSET_VERSION}`;
export const APP_ICON_MASKABLE = `/generated-app-icon-maskable-512.png?v=${APP_ASSET_VERSION}`;
export const APP_LOGO_FULL = APP_ICON_512;
export const APP_LOGO_ICON = APP_ICON_192;
export const APP_LOGO_CIRCLE = APP_ICON_512;
export const APP_LOGO_MARK = APP_ICON_192;
