export const APP_BRAND_NAME = "מנלו קודקס";
export const APP_BRAND_SHORT_NAME = "קודקס";
export const APP_BRAND_TAGLINE = "מערכת ניהול לקבלן בניין";
export const APP_DEFAULT_ORG_NAME = "מנלו בנייה";
export const APP_DRIVE_ROOT_FOLDER = "מנלו בנייה";
export const APP_PRODUCTION_URL = "https://menlo-codex.vercel.app";
export const APP_ASSET_VERSION = "2026-05-11-5";
export const APP_PWA_CACHE_VERSION = APP_ASSET_VERSION;
export const APP_LOGO_FULL = `/logo-icon.svg?v=${APP_ASSET_VERSION}`;
export const APP_LOGO_ICON = `/logo-icon.svg?v=${APP_ASSET_VERSION}`;
export const APP_LOGO_CIRCLE = `/logo-icon.svg?v=${APP_ASSET_VERSION}`;
export const APP_LOGO_MARK = `/logo-icon.svg?v=${APP_ASSET_VERSION}`;
